### ISSUE TITLE
Incompatibility with QGIS Server 2.99

### ISSUE THREAD

**Issue by elemoine** [qgis/qwc2#32]
I've come across what I think is an incompatibility with QGIS Server 2.99. With QGIS Server 2.99 leaf layers in `GetProjectSettings` responses do not have the `visible` attribute. So because of that the `themesConfig.js` script may not be able to create map thumbnails. The script indeed assumes that visible layers have the `visible` attribute set in the `GetProjectSettings` response. At this point I don't know whether this is a regression in QGIS Server 2.99.

**Comment by andreasneumann** [comment]
@elemoine I think this should be fixed in QGIS server. I will issue a report. I haven't yet tested QGIS server 2.99 yet, so I didn't notice, but now, with feature freeze approaching, I will test more thoroughly.

BTW: issues about qwc2 are recorded in the [qwc2-demo-app](https://github.com/qgis/qwc2-demo-app/issues) repo.

**Comment by elemoine** [comment]
This is being fixed in QGIS Server: https://github.com/qgis/QGIS/pull/5400.

**Comment by elemoine** [comment]
> BTW: issues about qwc2 are recorded in the qwc2-demo-app repo.

In that case, you may want to indicate that on the README, and also [disable Issues](https://help.github.com/articles/disabling-issues/) in this repo.
